services:
  js:
    build:
      context: ./docker/js
      args:
        - UID=1000
        - GID=1000
    # user: ${HOST_UID}:${HOST_GID}
    volumes:
      - ./front:/home/bun/front
    # これ、おかしいよ
    tty: true
    working_dir: /home/bun/front
    ports:
      - ${BIND_IP:-127.0.0.1}:5173:5173
      - ${BIND_IP:-127.0.0.1}:5555:5555
  pgsql:
    restart: always
    build:
      context: ./docker/db
      args:
        - UID=1000
        - GID=1000
      # volumes:
      # - ./docker/db/postgresql/initdb:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 5s
      timeout: 2s
      retries: 20
